-- 1. 대출 신청 메인 테이블
CREATE TABLE IF NOT EXISTS LOAN_APPLICATION (
    APPLICATION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(20,2) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    FILE_NAME VARCHAR(255),
    ADDRESS VARCHAR(500)
);

-- 2. 검색 성능 향상을 위한 인덱스
CREATE INDEX IF NOT EXISTS IDX_LOAN_CUSTOMER_ID ON LOAN_APPLICATION(CUSTOMER_ID);

-- 3. 관리자 심사 메모 테이블
CREATE TABLE IF NOT EXISTS LOAN_MEMO (
    MEMO_ID INT AUTO_INCREMENT PRIMARY KEY,
    APPLICATION_ID VARCHAR(50) NOT NULL,
    WRITER VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);