-- 기존 LOAN_APPLICATION 테이블 밑에 추가
CREATE TABLE IF NOT EXISTS LOAN_MEMO (
    MEMO_ID INT AUTO_INCREMENT PRIMARY KEY,
    APPLICATION_ID VARCHAR(50) NOT NULL,
    WRITER VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);