CREATE TABLE IF NOT EXISTS LOAN_APPLICATION (
    APPLICATION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(20,2) NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL
);